/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Poke.Poke;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;

/**
 *
 * @author Aluno
 */
public class CombateGUI extends javax.swing.JFrame {
    private Poke p1;
    private Poke p2;
    /**
     * Creates new form CombateGUI
     */
    public CombateGUI() {
        initComponents();
        setCenario();
    }
    
    public void setCenario(){
        ImageIcon imageBackground = new ImageIcon(getClass().getResource("/img/cenario.gif"));
        JLabel labelBackground = new JLabel(imageBackground);
        labelBackground.setBounds(0, 0, 1920, 1080);
        getContentPane().add(labelBackground);
    }
      public void setImage(){
      ImageIcon img = new ImageIcon();
      lblP1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GaloCururu/default.gif")));
      lblP2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Papaco/default.gif")));
      
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblP1Img = new javax.swing.JLabel();
        lblP2Img = new javax.swing.JLabel();
        lblP2Nome = new javax.swing.JLabel();
        lblP1Nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(19, 613));

        lblP1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GaloCururu/default.gif"))); // NOI18N

        lblP2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Papaco/default.gif"))); // NOI18N

        lblP2Nome.setText("jLabel1");

        lblP1Nome.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(lblP1Img)
                .addGap(389, 389, 389)
                .addComponent(lblP2Img, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(593, 593, 593)
                .addComponent(lblP1Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblP2Nome)
                .addGap(592, 592, 592))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP1Nome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblP2Nome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblP2Img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblP1Img))
                .addGap(234, 234, 234))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombateGUI().setVisible(true);
            }
        });
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblP1Img;
    private javax.swing.JLabel lblP1Nome;
    private javax.swing.JLabel lblP2Img;
    private javax.swing.JLabel lblP2Nome;
    // End of variables declaration//GEN-END:variables
}
