/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Poke.Poke;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.IIOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;

/**
 *
 * @author Aluno
 */
public class CombateGUI extends javax.swing.JFrame {
    private Poke p1;
    private Poke p2;
    /**
     * Creates new form CombateGUI
     */
    public CombateGUI() {
        initComponents();
        setCenario();
        //setImage();
    }
    
    public void setCenario(){
        ImageIcon imageBackground = new ImageIcon(getClass().getResource("/img/cenario.gif"));
        JLabel labelBackground = new JLabel(imageBackground);
        labelBackground.setBounds(0, 0, 1920, 1080);
        getContentPane().add(labelBackground);
    }
      public void setImage(Poke player){   
      lblP1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GaloCururu/default.gif")));
      if(player == p2){
        lblP2Img.setIcon(new ImageIcon(getClass().getResource(player.getImagePath())));
      }
      
      
    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblP1Img = new javax.swing.JLabel();
        lblP2Img = new javax.swing.JLabel();
        lblP2Nome = new javax.swing.JLabel();
        HpBarP2 = new javax.swing.JProgressBar();
        lblP1Nome1 = new javax.swing.JLabel();
        HpBarP1 = new javax.swing.JProgressBar();
        lblLvP2 = new javax.swing.JLabel();
        lblLvP1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(19, 613));

        lblP1Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GaloCururu/default.gif"))); // NOI18N

        lblP2Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Papaco/defaultIN.gif"))); // NOI18N

        lblP2Nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblP2Nome.setForeground(new java.awt.Color(255, 255, 255));
        lblP2Nome.setText("P2");

        HpBarP2.setValue(100);

        lblP1Nome1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblP1Nome1.setForeground(new java.awt.Color(255, 255, 255));
        lblP1Nome1.setText("P1");

        HpBarP1.setValue(100);

        lblLvP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLvP2.setForeground(new java.awt.Color(255, 255, 255));
        lblLvP2.setText("LV:1");

        lblLvP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLvP1.setForeground(new java.awt.Color(255, 255, 255));
        lblLvP1.setText("LV:1");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1702, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(515, 515, 515)
                                .addComponent(lblLvP1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HpBarP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(609, 609, 609)
                                .addComponent(lblP1Nome1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(464, 464, 464)
                                .addComponent(lblLvP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HpBarP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(556, 556, 556)
                                .addComponent(lblP2Nome))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblP1Img)
                        .addGap(269, 269, 269)
                        .addComponent(lblP2Img, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(468, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblP1Nome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HpBarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblP2Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HpBarP2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLvP2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLvP1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblP2Img)
                    .addComponent(lblP1Img))
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombateGUI().setVisible(true);
            }
        });
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar HpBarP1;
    private javax.swing.JProgressBar HpBarP2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLvP1;
    private javax.swing.JLabel lblLvP2;
    private javax.swing.JLabel lblP1Img;
    private javax.swing.JLabel lblP1Nome1;
    private javax.swing.JLabel lblP2Img;
    private javax.swing.JLabel lblP2Nome;
    // End of variables declaration//GEN-END:variables
}
